# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(username: "Richie", password: "password123")
User.create(username: "Guest", password: "password123")
User.create(username: "Johnny", password: "password123")
User.create(username: "John H", password: "password123")
User.create(username: "John P", password: "password123")
User.create(username: "John K", password: "password123")
User.create(username: "John D", password: "password123")
User.create(username: "John S", password: "password123")
User.create(username: "John W", password: "password123")
User.create(username: "John Q", password: "password123")
User.create(username: "John Z", password: "password123")
User.create(username: "John A", password: "password123")
User.create(username: "Joe B", password: "password123")
User.create(username: "Joe A", password: "password123")
User.create(username: "Joe C", password: "password123")
User.create(username: "Joe D", password: "password123")
User.create(username: "Joe E", password: "password123")
User.create(username: "Joe F", password: "password123")
User.create(username: "Joe G", password: "password123")
User.create(username: "Joe H", password: "password123")
User.create(username: "Joe I", password: "password123")
User.create(username: "Joe J", password: "password123")
User.create(username: "Joe K", password: "password123")
User.create(username: "Joe L", password: "password123")
User.create(username: "Joe M", password: "password123")
User.create(username: "Joe N", password: "password123")
User.create(username: "Joe O", password: "password123")
User.create(username: "Joe P", password: "password123")
User.create(username: "Joe Q", password: "password123")
User.create(username: "Joe R", password: "password123")
User.create(username: "Joe S", password: "password123")
User.create(username: "Joe T", password: "password123")
User.create(username: "Joe U", password: "password123")
User.create(username: "Joe V", password: "password123")
User.create(username: "Joe W", password: "password123")
User.create(username: "Joe X", password: "password123")
User.create(username: "Jose A", password: "password123")
User.create(username: "Jose B", password: "password123")
User.create(username: "Jose C", password: "password123")
User.create(username: "Jose D", password: "password123")
User.create(username: "Jose E", password: "password123")
User.create(username: "Jose F", password: "password123")
User.create(username: "Jose G", password: "password123")
User.create(username: "Jose H", password: "password123")
User.create(username: "Jose I", password: "password123")
User.create(username: "Jose J", password: "password123")
User.create(username: "Jose K", password: "password123")
User.create(username: "Jose L", password: "password123")
User.create(username: "Jose M", password: "password123")
User.create(username: "Jose N", password: "password123")
User.create(username: "Jose O", password: "password123")
User.create(username: "Jose P", password: "password123")
User.create(username: "Jose Q", password: "password123")
User.create(username: "Jose R", password: "password123")
User.create(username: "Jose S", password: "password123")
User.create(username: "Jose T", password: "password123")
User.create(username: "Jose U", password: "password123")
User.create(username: "Jose V", password: "password123")
User.create(username: "Jose W", password: "password123")
User.create(username: "Jose X", password: "password123")
User.create(username: "Jose Y", password: "password123")
User.create(username: "Jose Z", password: "password123")
User.create(username: "Jose Z", password: "password123")
User.create(username: "Mimi A", password: "password123")
User.create(username: "Mimi B", password: "password123")
User.create(username: "Mimi C", password: "password123")
User.create(username: "Mimi D", password: "password123")
User.create(username: "Mimi E", password: "password123")
User.create(username: "Mimi F", password: "password123")
User.create(username: "Mimi G", password: "password123")
User.create(username: "Mimi H", password: "password123")
User.create(username: "Mimi I", password: "password123")
User.create(username: "Mimi J", password: "password123")
User.create(username: "Mimi K", password: "password123")
User.create(username: "Mimi L", password: "password123")
User.create(username: "Mimi M", password: "password123")
User.create(username: "Mimi N", password: "password123")
User.create(username: "Mimi O", password: "password123")
User.create(username: "Mimi P", password: "password123")
User.create(username: "Mimi Q", password: "password123")
User.create(username: "Mimi R", password: "password123")
User.create(username: "Mimi S", password: "password123")
User.create(username: "Mimi T", password: "password123")
User.create(username: "Mimi U", password: "password123")
User.create(username: "Mimi V", password: "password123")
User.create(username: "Mimi W", password: "password123")
User.create(username: "Mimi X", password: "password123")
User.create(username: "Mimi Y", password: "password123")
User.create(username: "Mimi Z", password: "password123")
Post.create(user_id: 13, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377912/Javascript-debugging_msp1th.jpg", title: "true story")
Post.create(user_id: 1, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377890/binary_jyzeb8.png", title: "Which type are you!?!? ;)")
Post.create(user_id: 56, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377894/Chrome-Vs-Firefox-While-IE-Eats-Glue_wmw7vf.jpg", title: "browser brawl")
Post.create(user_id: 1, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473223637/1-hour-code_cetpiy.jpg", title: "that's me!")
Post.create(user_id: 22, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377899/identation_ucsts4.jpg", title: "the elusive software engineer")
Post.create(user_id: 33, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377917/joke--meme_two-type_zgomrk.jpg", title: "2 types of people...")
Post.create(user_id: 55, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377883/about-stdout_pnbb2c.jpg", title: "dictionary injection")

Post.create(user_id: 30, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/Life_Before_the_Computer1_yzvp9k.jpg", title: "Hey, how'd they get that pic of me??!?")

Post.create(user_id: 56, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377937/Programmers_txl5ki.png", title: "truth")

Post.create(user_id: 40, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/joke-html5_otjcdp.jpg", title: "that's how I check..")

Post.create(user_id: 54, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473377929/null_y3tsgm.jpg", title: "dufuq??!?")
Post.create(user_id: 50, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473223466/tip6_lgredr.png", title: "I can't...")

Post.create(user_id: 51, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387359/YryhF_yr6tam.jpg", title: "clap your hands!")

Post.create(user_id: 49, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387359/top20replies_aqydeg.jpg", title: "mmmhmmm....")

Post.create(user_id: 5, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387359/the_art_of_happy_programming_kozymy.png", title: "joy indeed")

Post.create(user_id: 14, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387360/programmer_cartoon_troll_jokes_programming_saved_the_world_mck9ji.jpg", title: "been there")

Post.create(user_id: 67, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/pointers_mgih3a.png", title: "I see what you did there...")

Post.create(user_id: 22, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/office-worker_athsjh.png", title: "yup")

Post.create(user_id: 10, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/joke-way-of-thinking_ovso06.jpg", title: "A programmer says...")

Post.create(user_id: 6, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/joke--comic_sleep-cycle_b7zgan.jpg", title: "unfortunately i do dream of code :(")

Post.create(user_id: 35, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/joke--comic_life-of-programmer_mjlqan.jpg", title: "that's the ticket")

Post.create(user_id: 62, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/joke--comic_f1_krzxle.jpg", title: "corny but cute")

Post.create(user_id: 33, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387358/imagesbug_20vs_20feature_small_bohglp.jpg", title: "I love new features!!!")

Post.create(user_id: 37, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387357/images-technology-fun-9_izo8ak.jpg", title: "Am I a n00b because I love my aquarium screensaver??")

Post.create(user_id: 61, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387357/e6166440222cf326b6ea3f7c08171987_gm166f.jpg", title: "PRESS MORE BUTTONS!!")

Post.create(user_id: 87, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387357/e49a83808d4fef70349fc23337edc38f_f2g1bd.jpg", title: "decisions, decisions...")

Post.create(user_id: 71, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387357/css-puns-wife_qef4du.jpg", title: "that's about right")

Post.create(user_id: 24, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387357/a974ecc2aa6e12ea217bcc21af9c24f6_wuvjuc.jpg", title: "Hmmmm.  That third one looks familiar...  ;)")

Post.create(user_id: 24, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387357/1519232-geek_poke02_nxyjak.jpg", title: "been there")


Post.create(user_id: 16, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387356/8237aa56-e138-11e3-8a7e-22000ab82dd9-large_vr0kw1.jpg", title: "THIS TIME WILL BE DIFFERENT!!!")

Post.create(user_id: 16, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387356/5077a1cf5ebc85d33c56f33599f55bdb_ndhqfd.jpg", title: "COOKIES!!!")

Post.create(user_id: 11, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387356/20bedda9a927eb7783727cd50fcf3a18_j36pwv.jpg", title: "Livin' la vida loca!!!")

Post.create(user_id: 11, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387356/9dfbd7e7c2083478e6b4091ee113a3aa_ehvsg9.jpg", title: "ahhh, movie hacking")

Post.create(user_id: 50, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387356/7e906b6eeac775ad40290f6d7a65f59c_f0tcrb.jpg", title: "my son")

Post.create(user_id: 50, image_url: "http://res.cloudinary.com/one001gag/image/upload/v1473387356/6a00d8341d3df553ef0162fd739fcc970d-800wi_sgcvao.jpg", title: "docs")


Comment.create(user_id: 33, post_id: 1, body: "This is great")
Comment.create(user_id: 27, post_id: 1, body: "LIKE!")
Comment.create(user_id: 11, post_id: 1, body: "I don't understand")
Comment.create(user_id: 36, post_id: 1, body: "This is awesome")
Comment.create(user_id: 21, post_id: 1, body: "lolz af")
Comment.create(user_id: 22, post_id: 1, body: "LOLROTFLMFAO")
Comment.create(user_id: 11, post_id: 2, body: "I see what u did there ;)")
Comment.create(user_id: 36, post_id: 2, body: "This is soooo awesome!")
Comment.create(user_id: 21, post_id: 2, body: "wth?  it says 10 but then only lists two???")
Comment.create(user_id: 22, post_id: 2, body: "10 is 2 in binary!!!")
Comment.create(user_id: 36, post_id: 3, body: "This is awesome")
Comment.create(user_id: 23, post_id: 3, body: "lolz af")
Comment.create(user_id: 22, post_id: 3, body: "LOLROTFLMFAO")
Comment.create(user_id: 36, post_id: 3, body: "awesome")
Comment.create(user_id: 23, post_id: 3, body: "lol")
Comment.create(user_id: 22, post_id: 3, body: "LOLROTFLMFAO")
Comment.create(user_id: 22, post_id: 3, body: "LOVE IT!")
Comment.create(user_id: 36, post_id: 4, body: "like")
Comment.create(user_id: 24, post_id: 5, body: "lolz")
Comment.create(user_id: 22, post_id: 6, body: "ROTFLMFAO")
Comment.create(user_id: 46, post_id: 7, body: "great")
Comment.create(user_id: 24, post_id: 8, body: "lol")
Comment.create(user_id: 22, post_id: 9, body: "hihi")
Comment.create(user_id: 22, post_id: 10, body: "nice")
Comment.create(user_id: 22, post_id: 11, body: "hahahaha")
Comment.create(user_id: 22, post_id: 12, body: "ok!!")
Comment.create(user_id: 22, post_id: 13, body: "yup")
Comment.create(user_id: 22, post_id: 14, body: ":)")
Comment.create(user_id: 22, post_id: 14, body: "love it")
Comment.create(user_id: 22, post_id: 15, body: "cool")
Comment.create(user_id: 22, post_id: 16, body: "nice brah")
Comment.create(user_id: 22, post_id: 17, body: "word")
Comment.create(user_id: 22, post_id: 18, body: "real nice")
Comment.create(user_id: 22, post_id: 19, body: "good one")

Comment.create(user_id: 33, post_id: 18, body: "This is great")
Comment.create(user_id: 27, post_id: 18, body: "LIKE!")
Comment.create(user_id: 11, post_id: 18, body: "I don't understand")
Comment.create(user_id: 36, post_id: 18, body: "This is awesome")
Comment.create(user_id: 21, post_id: 18, body: "lolz af")
Comment.create(user_id: 22, post_id: 18, body: "LOLROTFLMFAO")

Comment.create(user_id: 22, post_id: 12, body: "hahahaha")
Comment.create(user_id: 22, post_id: 12, body: "ok!!")
Comment.create(user_id: 22, post_id: 12, body: "yup")
Comment.create(user_id: 22, post_id: 12, body: ":)")
Comment.create(user_id: 22, post_id: 12, body: "love it")
Comment.create(user_id: 22, post_id: 12, body: "cool")
Comment.create(user_id: 22, post_id: 12, body: "nice brah")
Comment.create(user_id: 22, post_id: 12, body: "word")
Comment.create(user_id: 22, post_id: 12, body: "real nice")
Comment.create(user_id: 22, post_id: 12, body: "good one")



Vote.create(user_id: 20, post_id: 12, vote_value: 1)
Vote.create(user_id: 3, post_id: 12, vote_value: 1)
Vote.create(user_id: 4, post_id: 12, vote_value: 1)
Vote.create(user_id: 5, post_id: 12, vote_value: 1)
Vote.create(user_id: 6, post_id: 12, vote_value: 1)
Vote.create(user_id: 7, post_id: 12, vote_value: 1)
Vote.create(user_id: 8, post_id: 12, vote_value: 1)
Vote.create(user_id: 9, post_id: 12, vote_value: 1)
Vote.create(user_id: 10, post_id: 12, vote_value: 1)
Vote.create(user_id: 12, post_id: 12, vote_value: 1)
Vote.create(user_id: 11, post_id: 12, vote_value: 1)
Vote.create(user_id: 13, post_id: 12, vote_value: 1)
Vote.create(user_id: 14, post_id: 12, vote_value: 1)
Vote.create(user_id: 15, post_id: 12, vote_value: 1)
Vote.create(user_id: 16, post_id: 12, vote_value: 1)
Vote.create(user_id: 17, post_id: 12, vote_value: 1)
Vote.create(user_id: 20, post_id: 2, vote_value: 1)
Vote.create(user_id: 3, post_id: 2, vote_value: 1)
Vote.create(user_id: 4, post_id: 2, vote_value: 1)
Vote.create(user_id: 5, post_id: 2, vote_value: 1)
Vote.create(user_id: 6, post_id: 2, vote_value: 1)
Vote.create(user_id: 2, post_id: 3, vote_value: 1)
Vote.create(user_id: 3, post_id: 3, vote_value: 1)
Vote.create(user_id: 4, post_id: 3, vote_value: 1)
Vote.create(user_id: 5, post_id: 3, vote_value: 1)
Vote.create(user_id: 6, post_id: 3, vote_value: 1)
Vote.create(user_id: 12, post_id: 3, vote_value: 1)
Vote.create(user_id: 13, post_id: 3, vote_value: 1)
Vote.create(user_id: 14, post_id: 3, vote_value: 1)
Vote.create(user_id: 15, post_id: 3, vote_value: 1)
Vote.create(user_id: 16, post_id: 3, vote_value: 1)
Vote.create(user_id: 22, post_id: 3, vote_value: 1)
Vote.create(user_id: 23, post_id: 3, vote_value: 1)
Vote.create(user_id: 24, post_id: 3, vote_value: 1)
Vote.create(user_id: 25, post_id: 3, vote_value: 1)
Vote.create(user_id: 26, post_id: 3, vote_value: 1)
Vote.create(user_id: 32, post_id: 3, vote_value: 1)
Vote.create(user_id: 33, post_id: 3, vote_value: 1)
Vote.create(user_id: 34, post_id: 3, vote_value: 1)
Vote.create(user_id: 35, post_id: 3, vote_value: 1)
Vote.create(user_id: 36, post_id: 3, vote_value: 1)

Vote.create(user_id: 1, post_id: 32, vote_value: 1)
Vote.create(user_id: 2, post_id: 32, vote_value: 1)
Vote.create(user_id: 3, post_id: 32, vote_value: 1)
Vote.create(user_id: 4, post_id: 32, vote_value: 1)
Vote.create(user_id: 5, post_id: 32, vote_value: 1)
Vote.create(user_id: 6, post_id: 32, vote_value: 1)
Vote.create(user_id: 7, post_id: 32, vote_value: 1)
Vote.create(user_id: 8, post_id: 32, vote_value: 1)
Vote.create(user_id: 9, post_id: 32, vote_value: 1)
Vote.create(user_id: 10, post_id: 32, vote_value: 1)
Vote.create(user_id: 11, post_id: 32, vote_value: 1)
Vote.create(user_id: 12, post_id: 32, vote_value: 1)
Vote.create(user_id: 13, post_id: 32, vote_value: 1)
Vote.create(user_id: 14, post_id: 32, vote_value: 1)
Vote.create(user_id: 15, post_id: 32, vote_value: -1)
Vote.create(user_id: 16, post_id: 32, vote_value: 1)
Vote.create(user_id: 17, post_id: 32, vote_value: 1)
Vote.create(user_id: 18, post_id: 32, vote_value: 1)
Vote.create(user_id: 19, post_id: 32, vote_value: 1)
Vote.create(user_id: 20, post_id: 32, vote_value: 1)
Vote.create(user_id: 21, post_id: 32, vote_value: 1)
Vote.create(user_id: 22, post_id: 32, vote_value: 1)
Vote.create(user_id: 23, post_id: 32, vote_value: 1)
Vote.create(user_id: 24, post_id: 32, vote_value: 1)
Vote.create(user_id: 25, post_id: 32, vote_value: 1)
Vote.create(user_id: 26, post_id: 32, vote_value: 1)
Vote.create(user_id: 27, post_id: 32, vote_value: 1)
Vote.create(user_id: 28, post_id: 32, vote_value: 1)
Vote.create(user_id: 29, post_id: 32, vote_value: 1)
Vote.create(user_id: 30, post_id: 32, vote_value: 1)

Vote.create(user_id: 1, post_id: 30, vote_value: 1)
Vote.create(user_id: 2, post_id: 30, vote_value: 1)
Vote.create(user_id: 3, post_id: 30, vote_value: 1)
Vote.create(user_id: 4, post_id: 30, vote_value: 1)
Vote.create(user_id: 5, post_id: 30, vote_value: 1)
Vote.create(user_id: 6, post_id: 30, vote_value: 1)
Vote.create(user_id: 7, post_id: 30, vote_value: 1)
Vote.create(user_id: 8, post_id: 30, vote_value: 1)
Vote.create(user_id: 9, post_id: 30, vote_value: 1)
Vote.create(user_id: 10, post_id: 30, vote_value: 1)
Vote.create(user_id: 11, post_id: 30, vote_value: 1)
Vote.create(user_id: 12, post_id: 30, vote_value: 1)
Vote.create(user_id: 13, post_id: 30, vote_value: 1)
Vote.create(user_id: 14, post_id: 30, vote_value: 1)
Vote.create(user_id: 15, post_id: 30, vote_value: -1)
Vote.create(user_id: 16, post_id: 30, vote_value: 1)
Vote.create(user_id: 17, post_id: 30, vote_value: 1)
Vote.create(user_id: 18, post_id: 30, vote_value: 1)
Vote.create(user_id: 19, post_id: 30, vote_value: 1)
Vote.create(user_id: 20, post_id: 30, vote_value: 1)
Vote.create(user_id: 21, post_id: 30, vote_value: 1)
Vote.create(user_id: 22, post_id: 30, vote_value: 1)
Vote.create(user_id: 23, post_id: 30, vote_value: 1)
Vote.create(user_id: 24, post_id: 30, vote_value: 1)
Vote.create(user_id: 25, post_id: 30, vote_value: 1)
Vote.create(user_id: 26, post_id: 30, vote_value: 1)
Vote.create(user_id: 27, post_id: 30, vote_value: 1)
Vote.create(user_id: 28, post_id: 30, vote_value: 1)
Vote.create(user_id: 29, post_id: 30, vote_value: 1)
Vote.create(user_id: 30, post_id: 30, vote_value: 1)
Vote.create(user_id: 31, post_id: 30, vote_value: 1)
Vote.create(user_id: 32, post_id: 30, vote_value: 1)
Vote.create(user_id: 33, post_id: 30, vote_value: 1)
Vote.create(user_id: 34, post_id: 30, vote_value: 1)
Vote.create(user_id: 35, post_id: 30, vote_value: 1)
Vote.create(user_id: 36, post_id: 30, vote_value: 1)
Vote.create(user_id: 37, post_id: 30, vote_value: -1)
Vote.create(user_id: 38, post_id: 30, vote_value: -1)
Vote.create(user_id: 39, post_id: 30, vote_value: 1)
Vote.create(user_id: 40, post_id: 30, vote_value: 1)
Vote.create(user_id: 41, post_id: 30, vote_value: 1)


Vote.create(user_id: 1, post_id: 4, vote_value: 1)
Vote.create(user_id: 2, post_id: 4, vote_value: 1)
Vote.create(user_id: 3, post_id: 4, vote_value: 1)
Vote.create(user_id: 4, post_id: 4, vote_value: 1)
Vote.create(user_id: 5, post_id: 4, vote_value: 1)
Vote.create(user_id: 6, post_id: 4, vote_value: 1)
Vote.create(user_id: 7, post_id: 4, vote_value: 1)
Vote.create(user_id: 8, post_id: 4, vote_value: 1)
Vote.create(user_id: 9, post_id: 4, vote_value: 1)
Vote.create(user_id: 10, post_id: 4, vote_value: 1)
Vote.create(user_id: 11, post_id: 4, vote_value: 1)
Vote.create(user_id: 12, post_id: 4, vote_value: 1)
Vote.create(user_id: 13, post_id: 4, vote_value: 1)
Vote.create(user_id: 14, post_id: 4, vote_value: 1)
Vote.create(user_id: 15, post_id: 4, vote_value: -1)
Vote.create(user_id: 16, post_id: 4, vote_value: 1)
Vote.create(user_id: 17, post_id: 4, vote_value: 1)
Vote.create(user_id: 18, post_id: 4, vote_value: 1)
Vote.create(user_id: 19, post_id: 4, vote_value: 1)
Vote.create(user_id: 20, post_id: 4, vote_value: 1)
Vote.create(user_id: 21, post_id: 4, vote_value: 1)
Vote.create(user_id: 22, post_id: 4, vote_value: 1)
