# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(username: "Richie", password: "password123")
User.create(username: "Guest", password: "password123")
User.create(username: "Johnny", password: "password123")
User.create(username: "John H", password: "password123")
User.create(username: "John P", password: "password123")
User.create(username: "John K", password: "password123")
User.create(username: "John D", password: "password123")
User.create(username: "John S", password: "password123")
User.create(username: "John W", password: "password123")
User.create(username: "John Q", password: "password123")
User.create(username: "John Z", password: "password123")
User.create(username: "John A", password: "password123")
User.create(username: "Joe B", password: "password123")
User.create(username: "Joe A", password: "password123")
User.create(username: "Joe C", password: "password123")
User.create(username: "Joe D", password: "password123")
User.create(username: "Joe E", password: "password123")
User.create(username: "Joe F", password: "password123")
User.create(username: "Joe G", password: "password123")
User.create(username: "Joe H", password: "password123")
User.create(username: "Joe I", password: "password123")
User.create(username: "Joe J", password: "password123")
User.create(username: "Joe K", password: "password123")
User.create(username: "Joe L", password: "password123")
User.create(username: "Joe M", password: "password123")
User.create(username: "Joe N", password: "password123")
User.create(username: "Joe O", password: "password123")
User.create(username: "Joe P", password: "password123")
User.create(username: "Joe Q", password: "password123")
User.create(username: "Joe R", password: "password123")
User.create(username: "Joe S", password: "password123")
User.create(username: "Joe T", password: "password123")
User.create(username: "Joe U", password: "password123")
User.create(username: "Joe V", password: "password123")
User.create(username: "Joe W", password: "password123")
User.create(username: "Joe X", password: "password123")
User.create(username: "Jose A", password: "password123")
User.create(username: "Jose B", password: "password123")
User.create(username: "Jose C", password: "password123")
User.create(username: "Jose D", password: "password123")
User.create(username: "Jose E", password: "password123")
User.create(username: "Jose F", password: "password123")
User.create(username: "Jose G", password: "password123")
User.create(username: "Jose H", password: "password123")
User.create(username: "Jose I", password: "password123")
User.create(username: "Jose J", password: "password123")
User.create(username: "Jose K", password: "password123")
User.create(username: "Jose L", password: "password123")
User.create(username: "Jose M", password: "password123")
User.create(username: "Jose N", password: "password123")
User.create(username: "Jose O", password: "password123")
User.create(username: "Jose P", password: "password123")
User.create(username: "Jose Q", password: "password123")
User.create(username: "Jose R", password: "password123")
User.create(username: "Jose S", password: "password123")
User.create(username: "Jose T", password: "password123")
User.create(username: "Jose U", password: "password123")
User.create(username: "Jose V", password: "password123")
User.create(username: "Jose W", password: "password123")
User.create(username: "Jose X", password: "password123")
User.create(username: "Jose Y", password: "password123")
User.create(username: "Jose Z", password: "password123")
User.create(username: "Jose Z", password: "password123")
User.create(username: "Mimi A", password: "password123")
User.create(username: "Mimi B", password: "password123")
User.create(username: "Mimi C", password: "password123")
User.create(username: "Mimi D", password: "password123")
User.create(username: "Mimi E", password: "password123")
User.create(username: "Mimi F", password: "password123")
User.create(username: "Mimi G", password: "password123")
User.create(username: "Mimi H", password: "password123")
User.create(username: "Mimi I", password: "password123")
User.create(username: "Mimi J", password: "password123")
User.create(username: "Mimi K", password: "password123")
User.create(username: "Mimi L", password: "password123")
User.create(username: "Mimi M", password: "password123")
User.create(username: "Mimi N", password: "password123")
User.create(username: "Mimi O", password: "password123")
User.create(username: "Mimi P", password: "password123")
User.create(username: "Mimi Q", password: "password123")
User.create(username: "Mimi R", password: "password123")
User.create(username: "Mimi S", password: "password123")
User.create(username: "Mimi T", password: "password123")
User.create(username: "Mimi U", password: "password123")
User.create(username: "Mimi V", password: "password123")
User.create(username: "Mimi W", password: "password123")
User.create(username: "Mimi X", password: "password123")
User.create(username: "Mimi Y", password: "password123")
User.create(username: "Mimi Z", password: "password123")
Post.create(user_id: 13, image_url: "http://devhumor.com/content/uploads//images/August2016/Javascript-debugging.jpg", title: "true story")
Post.create(user_id: 1, image_url: "https://theshpitz.files.wordpress.com/2010/03/binary.png", title: "Which type are you!?!? ;)")
Post.create(user_id: 56, image_url: "http://devhumor.com/content/uploads//images/August2016/Chrome-Vs-Firefox-While-IE-Eats-Glue.jpg", title: "browser brawl")
Post.create(user_id: 1, image_url: "http://devhumor.com/content/uploads//images/May2016/1-hour-code.jpg", title: "that's me!")
Post.create(user_id: 22, image_url: "http://devhumor.com/content/uploads//images/August2016/identation.jpg", title: "the elusive software engineer")
Post.create(user_id: 33, image_url: "http://media02.hongkiat.com/programming-jokes/joke--meme_two-type.jpg", title: "2 types of people...")
Post.create(user_id: 55, image_url: "http://devhumor.com/content/uploads//images/August2016/about-stdout.jpg", title: "dictionary injection")
Post.create(user_id: 56, image_url: "http://devhumor.com/content/uploads//images/August2016/Programmers.png", title: "truth")
Post.create(user_id: 54, image_url: "http://devhumor.com/content/uploads//images/August2016/null.jpg", title: "dufuq??!?")
